name = "suhba"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "/"

[build.environment_variables]
NODE_VERSION = "18"
SKIP_DEPENDENCY_INSTALL = "true"

[[pages_build_output_dir]]
path = "./build"